# Configuración de entrenamiento YOLOv8 - Detección de Caries
model: yolov8s.pt
imgsz: 640
epochs: 100
batch: 16
patience: 20       # early stopping
conf: 0.25         # umbral de confianza en inferencia
iou: 0.7           # IoU threshold para NMS

# Roboflow
workspace: dannys-workspace-p5vnc
project: data_caries
version: 3

# Clases
classes:
  0: caries leve
  1: caries moderada
  2: caries severa
  3: sin caries
